services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  backend:
    build:
      context: ./gooddeeds-api
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/database?schema=public
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    networks:
      - my_network

  frontend:
    build:
      context: ./gooddeeds
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      NEXTAUTH_SECRET: supersecretcode
      NEXTAUTH_URL: http://localhost:3000 
      NEXT_PUBLIC_API_URL: http://localhost/api
    ports:
      - "3000:3000"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - my_network


volumes:
  postgres_data:

networks:
  my_network: